### ISSUE TITLE
opn command open empty vscode

### ISSUE THREAD

**Issue by ravecat** [sindresorhus/opn-cli#11]
Use app based on create-react-app and try to open html-file with second command
```
    "test": "react-scripts test --passWithNoTests",
    "test:coverage": "yarn test --coverage && opn ./coverage/lcov-report/index.html",
```

But only open vscode empty window, try to set brower like this
```
"test:coverage": "yarn test --coverage && opn ./coverage/lcov-report/index.html -- 'google chrome'",
```

And get error
>events.js:167
      throw er; // Unhandled 'error' event
      ^

>Error: spawn google chrome ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
>Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Current opn version
`"opn-cli": "^4.0.0",`

System
```
node v10.15.0
Debian GNU/Linux 9 (stretch)
```

**Comment by peterpetre** [comment]
I use the renamed `open-cli` and i do
```
"test:coverage": "yarn test --coverage && open-cli ./coverage/lcov-report/index.html -- 'google chrome'",
```
and works fine
