### ISSUE TITLE
SyntaxError: use of const in strict mode.

### ISSUE THREAD

**Issue by roccomuso** [sindresorhus/opn-cli#8]
I'm having this error on Windows 10:

`
 const meow = require('meow');
 ^^^^^

 SyntaxError: Use of const in strict mode.
     at exports.runInThisContext (vm.js:73:16)
     at Module._compile (module.js:443:25)
     at Object.Module._extensions..js (module.js:478:10)
     at Module.load (module.js:355:32)
     at Function.Module._load (module.js:310:12)
     at Function.Module.runMain (module.js:501:10)
     at startup (node.js:129:16)
     at node.js:814:3
`

**Comment by sindresorhus** [comment]
Upgrade Node.js
